version: '3'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    restart: unless-stopped
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=password123
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
    command: bash -c "rm -r $SONARQUBE-HOME/temp"
    ports:
      - "9000:9000"
      - "9092:9092"

  db:
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=sonarqube

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - internal

  minio:
    image: minio/minio
    ports:
      - "9001:9000"
    volumes:
      - ./datastore:/data
    environment:
      - "MINIO_ROOT_USER=minio"
      - "MINIO_ROOT_PASSWORD=minio123"
    command: server /data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minio minio123;
      /usr/bin/mc mb myminio/diogo;
      /usr/bin/mc policy set public myminio/diogo;
      exit 0;
      "