global:
  scrape_interval:     20s
  evaluation_interval: 15s

  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'metricas'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: /metrics
    scheme: http